BEGIN;

ALTER TABLE users 
  ALTER COLUMN iduser ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE "group" RENAME TO groups;
ALTER TABLE groups 
  ALTER COLUMN idgroup ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE movie 
  ALTER COLUMN "idMovie" ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE favorite 
  ALTER COLUMN "idFavorite" ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE review 
  ALTER COLUMN "idReview" ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE showtime 
  ALTER COLUMN "idShowtime" ADD GENERATED ALWAYS AS IDENTITY;

COMMIT;